export const LIVE_HTML=String.raw`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Live screen · Avi G Gallery</title><style>body{font:16px system-ui;background:#faf9f6;color:#252823;margin:24px}header{display:flex;gap:18px;align-items:center;flex-wrap:wrap}h1{font:28px Georgia}button,a{font:inherit;color:inherit}button{padding:8px 16px}#screen{display:block;max-width:100%;max-height:80vh;margin:20px auto;background:#111}#status{min-height:24px}small{color:#666}</style></head><body><header><h1>Live screen</h1><a href="/">Gallery</a><button id="start">Connect</button><button id="stop" disabled>Disconnect</button></header><p id="status" role="status">Connect while the sharing Mac is on the same local network.</p><small>Live only · No audio · No recordings · One viewer at a time</small><img id="screen" alt="Live shared screen" hidden><script>
let ws,pc,channel,parts=[],size=0,lastFrame=0,timeout;const $=id=>document.getElementById(id),status=t=>$('status').textContent=t;
function clearFrame(){parts=[];size=0;$('screen').hidden=true;$('screen').removeAttribute('src');}
function closePeer(){clearTimeout(timeout);if(channel)channel.close();channel=null;if(pc)pc.close();pc=null;clearFrame();}
function stop(){if(ws){ws.onclose=null;ws.close();ws=null;}closePeer();$('start').disabled=false;$('stop').disabled=true;status('Disconnected.');}
async function gather(peer){if(peer.iceGatheringState==='complete')return;await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('Local network connection timed out.')),10000);peer.addEventListener('icegatheringstatechange',()=>{if(peer.iceGatheringState==='complete'){clearTimeout(t);resolve();}});});}
async function signal(m){if(m.type==='peer-left'){closePeer();status('Sharing Mac disconnected.');return;}if(m.type!=='offer'){if(m.type==='waiting')status('Waiting for the sharing Mac…');return;}
closePeer();const peer=pc=new RTCPeerConnection({iceServers:[]});peer.onconnectionstatechange=()=>{if(peer!==pc)return;if(['failed','disconnected','closed'].includes(peer.connectionState)){clearFrame();status('Connection interrupted. Disconnect and reconnect; check both Macs are on the same network.');}};
peer.ondatachannel=e=>{channel=e.channel;channel.onmessage=e=>{if(typeof e.data!=='string'||e.data.length>25000)return stop();if(e.data==='begin'){parts=[];size=0;return;}if(e.data==='end'){if(size&&size<=400000){$('screen').src='data:image/jpeg;base64,'+parts.join('');$('screen').hidden=false;lastFrame=Date.now();status('Live · about 3 frames per second');}parts=[];size=0;return;}size+=e.data.length;if(size>400000)return stop();parts.push(e.data);};};
await peer.setRemoteDescription(m);await peer.setLocalDescription(await peer.createAnswer());await gather(peer);if(pc===peer&&ws?.readyState===1)ws.send(JSON.stringify({type:'answer',sdp:peer.localDescription.sdp}));timeout=setTimeout(()=>{if(pc===peer&&peer.connectionState!=='connected'){clearFrame();status('Could not connect directly. Check local-network permissions and Wi-Fi client isolation.');}},20000);}
$('start').onclick=()=>{stop();$('start').disabled=true;$('stop').disabled=false;status('Connecting…');ws=new WebSocket('wss://'+location.host+'/api/live/viewer');ws.onmessage=e=>{signal(JSON.parse(e.data)).catch(e=>{stop();status(e.message);});};ws.onclose=()=>{stop();status('Session ended or access denied. Sign in as admin and reconnect. Sessions last up to 30 minutes.');};};$('stop').onclick=stop;addEventListener('pagehide',stop);setInterval(()=>{if(lastFrame&&Date.now()-lastFrame>5000&&!$('screen').hidden){clearFrame();status('Waiting for a current frame…');}},1000);
</script></body></html>`;
