export const LIVE_HTML=String.raw`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Live screen · Avi G Gallery</title><style>body{font:16px system-ui;background:#faf9f6;color:#252823;margin:24px}header{display:flex;gap:18px;align-items:center;flex-wrap:wrap}h1{font:28px Georgia}button,a{font:inherit;color:inherit}button{padding:8px 16px}#screen,#video{display:block;max-width:100%;max-height:80vh;margin:20px auto;background:#111}[hidden]{display:none!important}#status{min-height:24px}small{color:#666}</style></head><body><header><h1 id="title">Live screen</h1><a href="/">Gallery</a><a href="/live?mode=aiortc-test">aiortc test</a><button id="start">Connect</button><button id="stop" disabled>Disconnect</button></header><p id="status" role="status">Connect while the sharing Mac is on the same local network.</p><small>Live only · No audio · No recordings · One viewer at a time</small><img id="screen" alt="Live shared screen" hidden><video id="video" autoplay muted playsinline aria-label="aiortc test video" hidden></video><script>
let ws,pc,channel,parts=[],size=0,lastFrame=0,timeout,retryTimer,wanted=true,retryDelay=60000;const $=id=>document.getElementById(id),status=t=>$('status').textContent=t;
const testMode=new URLSearchParams(location.search).get('mode')==='aiortc-test';if(testMode)$('title').textContent='aiortc transport test';
function clearFrame(){parts=[];size=0;$('screen').hidden=true;$('screen').removeAttribute('src');$('video').hidden=true;}
function closePeer(){clearTimeout(timeout);if(channel)channel.close();channel=null;if(pc)pc.close();pc=null;$('video').srcObject=null;clearFrame();}
function disconnect(){if(ws){ws.onclose=null;ws.close();ws=null;}closePeer();$('start').disabled=false;$('stop').disabled=true;status('Disconnected.');}
function stop(){wanted=false;clearTimeout(retryTimer);disconnect();}
function retry(message){disconnect();if(!wanted)return;clearTimeout(retryTimer);status(message+' Retrying automatically…');$('stop').disabled=false;retryTimer=setTimeout(connect,retryDelay);retryDelay=Math.min(retryDelay*2,300000);}
async function gather(peer){if(peer.iceGatheringState==='complete')return;await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('Local network connection timed out.')),10000);peer.addEventListener('icegatheringstatechange',()=>{if(peer.iceGatheringState==='complete'){clearTimeout(t);resolve();}});});}
async function signal(m){if(m.type==='peer-left'){closePeer();status('Sharing Mac disconnected.');return;}if(m.type!=='offer'){if(m.type==='waiting')status('Waiting for the sharing Mac…');return;}
closePeer();const peer=pc=new RTCPeerConnection({iceServers:[]});peer.onconnectionstatechange=()=>{if(peer!==pc)return;if(['failed','disconnected','closed'].includes(peer.connectionState)){retry('Connection interrupted.');}};
peer.ontrack=e=>{if(peer!==pc||e.track.kind!=='video')return;const video=$('video');video.srcObject=new MediaStream([e.track]);
const frame=()=>{if(peer!==pc)return;lastFrame=Date.now();retryDelay=60000;video.hidden=false;$('screen').hidden=true;status('Live · aiortc test pattern (not your screen)');if(video.requestVideoFrameCallback)video.requestVideoFrameCallback(frame);};
if(video.requestVideoFrameCallback)video.requestVideoFrameCallback(frame);else video.ontimeupdate=frame;
video.play().catch(()=>{if(peer===pc)status('Video playback blocked by browser. Allow autoplay and reconnect.');});};
peer.ondatachannel=e=>{channel=e.channel;channel.onmessage=e=>{if(typeof e.data!=='string'||e.data.length>25000)return stop();if(e.data==='begin'){parts=[];size=0;return;}if(e.data==='end'){if(size&&size<=400000){$('screen').src='data:image/jpeg;base64,'+parts.join('');$('screen').hidden=false;lastFrame=Date.now();retryDelay=60000;status('Live · about 3 frames per second');}parts=[];size=0;return;}size+=e.data.length;if(size>400000)return stop();parts.push(e.data);};};
await peer.setRemoteDescription(m);await peer.setLocalDescription(await peer.createAnswer());await gather(peer);if(pc===peer&&ws?.readyState===1)ws.send(JSON.stringify({type:'answer',sdp:peer.localDescription.sdp}));timeout=setTimeout(()=>{if(pc===peer&&peer.connectionState!=='connected'){retry('Could not connect directly. Check local-network permissions and Wi-Fi client isolation.');}},20000);}
function connect(){if(!wanted)return;clearTimeout(retryTimer);disconnect();$('start').disabled=true;$('stop').disabled=false;status('Connecting…');const socket=ws=new WebSocket('wss://'+location.host+'/api/live/viewer'+(testMode?'?mode=aiortc-test':''));socket.onmessage=e=>{if(socket!==ws)return;try{signal(JSON.parse(e.data)).catch(e=>{if(socket===ws)retry(e.message);});}catch{stop();status('Invalid connection message.');}};socket.onclose=e=>{if(socket!==ws)return;if(e.code===1008){stop();status('Session rejected. Sign in as admin and reconnect.');return;}retry('Session ended or unavailable. Check admin sign-in if this persists.');};}
$('start').onclick=()=>{wanted=true;retryDelay=60000;connect();};$('stop').onclick=stop;addEventListener('pagehide',stop);setInterval(()=>{if(lastFrame&&Date.now()-lastFrame>5000&&(!$('screen').hidden||!$('video').hidden)){clearFrame();status('Waiting for a current frame…');}},1000);
connect();
</script></body></html>`;
